language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install qemu-kvm
  - export PATH=/home/travis/gopath/bin:$PATH
  - go get gopkg.in/check.v1

go_import_path: github.com/mikelangelo-project/capstan

install:
  - ./install
